steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'dev/ingress.yaml']
  env:
    - 'CLOUDSDK_CONTAINER_CLUSTER=phading-cluster'
    - 'CLOUDSDK_COMPUTE_REGION=us-central1'
options:
  logging: CLOUD_LOGGING_ONLY
